{% set name = "amazon-sagemaker-jupyter-ai-q-developer" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon_sagemaker_jupyter_ai_q_developer-{{ version }}.tar.gz
  sha256: 7ce10471067ef7f6c4f94043743df9c7659dce106c694c77c3c15fccbe5b16a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.6

test:
  imports:
    - amazon_sagemaker_jupyter_ai_q_developer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker/
  summary: Amazon SageMaker Jupyter Extension for Q Developer
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bhadrip
    - kumarnzt
    - gogakoreli
